#!/usr/bin/env python3
"""Ornith-1.5 Spark tune: language-only, MTP n=1/2/3, coding seqs, YaRN.

Writes JSONL to /opt/spark/run/ornith15-tune.jsonl and a summary at the end.
Designed to run on sparky while inference is otherwise idle.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path("/opt/spark")
SERVICE = ROOT / "services" / "eugr-ornith-ai-ornith-1-5-35b-a3b-nvfp4-b12x-eugr.yaml"
OUT = ROOT / "run" / "ornith15-tune.jsonl"
PROFILE = "ornith-ai-ornith-1-5-35b-a3b-nvfp4-b12x-eugr"
MODEL = "ornith-1.5-35b-a3b-nvfp4"
URL = "http://127.0.0.1:8000/v1/chat/completions"
MODELS_URL = "http://127.0.0.1:8000/v1/models"
HEALTH_URL = "http://127.0.0.1:8000/health"
METRICS_URL = "http://127.0.0.1:8000/metrics"
NATIVE = 262144

CODING = (
    "Write a Python function `merge_intervals(intervals: list[list[int]]) -> "
    "list[list[int]]` that merges overlapping inclusive intervals. Include a "
    "short docstring, type hints, and 4 assert-based tests in "
    '`if __name__ == "__main__":`. Do not explain. Output only code.'
)
FACTS = "Write a numbered list of 32 short facts about mixture-of-experts models."


def log(msg: str) -> None:
    print(msg, flush=True)


def record(row: dict) -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row) + "\n")
    log("RECORD " + json.dumps(row)[:500])


def yarn_overrides(max_len: int) -> str:
    factor = max_len / NATIVE
    payload = {
        "text_config": {
            "max_position_embeddings": int(max_len),
            "rope_parameters": {
                "rope_type": "yarn",
                "factor": factor,
                "original_max_position_embeddings": NATIVE,
                "mrope_interleaved": True,
                "mrope_section": [11, 11, 10],
                "partial_rotary_factor": 0.25,
                "rope_theta": 10000000,
            },
        }
    }
    raw = json.dumps(payload, separators=(",", ":"))
    escaped = raw.replace("{", "{{").replace("}", "}}")
    return f"    --hf-overrides '{escaped}' \\\n"


def write_service(
    *,
    spec_tokens: int,
    max_num_seqs: int,
    max_model_len: int,
    yarn: bool,
) -> None:
    yarn_line = yarn_overrides(max_model_len) if yarn else ""
    text = f"""# Ornith-1.5-35B-A3B NVFP4 on eugr/spark-vllm-b12x.
# Generated by scripts/ornith15-tune.py — do not hand-edit mid-sweep.
recipe_version: "1"
name: ornith-ai-ornith-1-5-35b-a3b-nvfp4-b12x-eugr
description: >-
  Ornith-1.5-35B-A3B NVFP4 + in-checkpoint MTP on eugr/spark-vllm-b12x
  (Mia b12x W4A16 overlays), text-only.

model: ornith-ai/Ornith-1.5-35B-A3B-NVFP4
container: eugr/spark-vllm-b12x:latest
skip_default_mods: true

volumes:
  - /opt/spark/mods/eugr-b12x-w4a16/kernel.py:/usr/local/lib/python3.12/dist-packages/b12x/moe/_shared/kernels/w4a16/kernel.py:ro
  - /opt/spark/mods/eugr-b12x-w4a16/route_pack.py:/usr/local/lib/python3.12/dist-packages/b12x/moe/_shared/kernels/w4a16/route_pack.py:ro

defaults:
  port: 8000
  host: 0.0.0.0
  tensor_parallel: 1
  gpu_memory_utilization: 0.85
  max_model_len: {max_model_len}
  max_num_seqs: {max_num_seqs}
  max_num_batched_tokens: 8192
  spec_tokens: {spec_tokens}

command: |
  vllm serve /models/ornith-ai/ornith-1.5-35b-a3b/nvfp4 \\
    --host {{host}} \\
    --port {{port}} \\
    --served-model-name ornith-1.5-35b-a3b-nvfp4 \\
    --tensor-parallel-size {{tensor_parallel}} \\
    --trust-remote-code \\
    --language-model-only \\
    --enable-prefix-caching \\
    --enable-chunked-prefill \\
    --spec-method mtp \\
    --spec-tokens {{spec_tokens}} \\
    --max-num-seqs {{max_num_seqs}} \\
    --max-num-batched-tokens {{max_num_batched_tokens}} \\
    --moe-backend b12x \\
    --gpu-memory-utilization {{gpu_memory_utilization}} \\
    --max-model-len {{max_model_len}} \\
{yarn_line}    --enable-auto-tool-choice \\
    --tool-call-parser qwen3_xml \\
    --reasoning-parser qwen3
"""
    SERVICE.write_text(text, encoding="utf-8")
    log(f"wrote {SERVICE} spec_tokens={spec_tokens} seqs={max_num_seqs} ctx={max_model_len} yarn={yarn}")


def sh(args: list[str], timeout: int = 120) -> subprocess.CompletedProcess:
    log("+ " + " ".join(args))
    return subprocess.run(args, capture_output=True, text=True, timeout=timeout)


def http_json(url: str, payload: dict | None = None, timeout: int = 180):
    data = None if payload is None else json.dumps(payload).encode()
    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"} if data else {},
        method="GET" if data is None else "POST",
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode())


def ready() -> dict | None:
    try:
        payload = http_json(MODELS_URL, timeout=5)
    except Exception:
        return None
    data = (payload or {}).get("data") or []
    if not data:
        return None
    return data[0]


def wait_ready(timeout_s: int = 1200) -> dict:
    deadline = time.time() + timeout_s
    last = ""
    while time.time() < deadline:
        row = ready()
        if row:
            return row
        try:
            logs = sh(["docker", "logs", "--tail", "8", "vllm_node"], timeout=20)
            tail = (logs.stdout or logs.stderr or "").strip().splitlines()[-1:]
            msg = tail[0] if tail else ""
            if msg and msg != last:
                log("log: " + msg[:240])
                last = msg
            running = sh(["docker", "ps", "-q", "-f", "name=^vllm_node$"], timeout=10)
            if not (running.stdout or "").strip():
                died = sh(["docker", "logs", "--tail", "60", "vllm_node"], timeout=20)
                raise RuntimeError(
                    "vllm_node exited\n" + (died.stdout or "")[-2500:] + (died.stderr or "")[-800:]
                )
        except RuntimeError:
            raise
        except Exception as e:
            log(f"wait probe: {e}")
        time.sleep(8)
    raise TimeoutError(f"engine not ready after {timeout_s}s")


def kv_info() -> dict:
    try:
        raw = urllib.request.urlopen(METRICS_URL, timeout=10).read().decode()
    except Exception as e:
        return {"error": str(e)}
    out: dict = {}
    m = re.search(r'kv_cache_size_tokens="(\d+)"', raw)
    if m:
        out["kv_tokens"] = int(m.group(1))
    m = re.search(r'kv_cache_max_concurrency="([^"]+)"', raw)
    if m:
        out["kv_max_concurrency"] = float(m.group(1))
    m = re.search(r'num_gpu_blocks="(\d+)"', raw)
    if m:
        out["num_gpu_blocks"] = int(m.group(1))
    m = re.search(r'cache_dtype="([^"]+)"', raw)
    if m:
        out["cache_dtype"] = m.group(1)
    m = re.search(r'gpu_memory_utilization="([^"]+)"', raw)
    if m:
        out["gpu_memory_utilization"] = float(m.group(1))
    hits = re.findall(r"^(vllm:[A-Za-z0-9_]*spec[A-Za-z0-9_]*)\{[^}]*\} ([0-9.eE+-]+)", raw, re.M)
    if hits:
        out["spec_metrics"] = {k: float(v) for k, v in hits[:12]}
    return out


def chat(name: str, prompt: str, max_tokens: int = 512) -> dict:
    body = {
        "model": MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": max_tokens,
        "temperature": 0,
        "stream": False,
        "chat_template_kwargs": {"enable_thinking": False},
    }
    t0 = time.perf_counter()
    try:
        payload = http_json(URL, body, timeout=300)
        err = None
    except Exception as e:
        elapsed = time.perf_counter() - t0
        return {
            "name": name,
            "ok": False,
            "error": str(e),
            "elapsed_s": round(elapsed, 3),
        }
    elapsed = time.perf_counter() - t0
    usage = payload.get("usage") or {}
    completion = int(usage.get("completion_tokens") or 0)
    prompt_tok = int(usage.get("prompt_tokens") or 0)
    text = ((payload.get("choices") or [{}])[0].get("message") or {}).get("content") or ""
    return {
        "name": name,
        "ok": True,
        "elapsed_s": round(elapsed, 3),
        "prompt_tokens": prompt_tok,
        "completion_tokens": completion,
        "tok_s": round(completion / elapsed, 2) if elapsed and completion else 0.0,
        "preview": text[:160].replace("\n", " / "),
    }


def launch(variant: dict) -> dict:
    write_service(
        spec_tokens=int(variant["spec_tokens"]),
        max_num_seqs=int(variant["max_num_seqs"]),
        max_model_len=int(variant["max_model_len"]),
        yarn=bool(variant.get("yarn")),
    )
    down = sh(["spark", "inference", "down"], timeout=180)
    log((down.stdout or "")[-400:] + (down.stderr or "")[-200:])
    time.sleep(3)
    up_cmd = ["spark", "inference", "up", PROFILE]
    if variant.get("yarn"):
        preset = "yarn_1m" if int(variant["max_model_len"]) >= 1048576 else "yarn_512k"
        up_cmd.extend(["--preset", preset])
    elif int(variant.get("max_num_seqs") or 24) <= 4:
        up_cmd.extend(["--preset", "coding"])
    up = sh(up_cmd, timeout=180)
    log((up.stdout or "")[-600:] + (up.stderr or "")[-300:])
    if up.returncode != 0:
        raise RuntimeError(f"spark inference up failed: {up.stderr or up.stdout}")
    info = wait_ready()
    return info


def run_variant(variant: dict) -> dict:
    log("=" * 72)
    log(f"VARIANT {variant['id']}")
    t0 = time.perf_counter()
    try:
        info = launch(variant)
        boot_s = round(time.perf_counter() - t0, 1)
        kv = kv_info()
        warmup = chat("warmup", "say hi", 16)
        coding = chat("coding", CODING, 512)
        facts = chat("facts", FACTS, 512)
        row = {
            "id": variant["id"],
            "ok": True,
            "variant": variant,
            "boot_s": boot_s,
            "max_model_len_live": info.get("max_model_len"),
            "kv": kv,
            "warmup": warmup,
            "coding": coding,
            "facts": facts,
        }
        record(row)
        return row
    except Exception as e:
        row = {
            "id": variant["id"],
            "ok": False,
            "variant": variant,
            "error": str(e)[-3000:],
            "elapsed_s": round(time.perf_counter() - t0, 1),
        }
        record(row)
        return row


def main() -> int:
    variants = [
        {
            "id": "lmo_n1_s24_256k",
            "spec_tokens": 1,
            "max_num_seqs": 24,
            "max_model_len": NATIVE,
            "yarn": False,
        },
        {
            "id": "lmo_n2_s24_256k",
            "spec_tokens": 2,
            "max_num_seqs": 24,
            "max_model_len": NATIVE,
            "yarn": False,
        },
        {
            "id": "lmo_n3_s24_256k",
            "spec_tokens": 3,
            "max_num_seqs": 24,
            "max_model_len": NATIVE,
            "yarn": False,
        },
    ]
    results = [run_variant(v) for v in variants]

    ok_n = [r for r in results if r.get("ok") and (r.get("coding") or {}).get("ok")]
    winner = None
    if ok_n:
        winner = max(ok_n, key=lambda r: float((r.get("coding") or {}).get("tok_s") or 0))
        log(f"MTP winner by coding tok/s: {winner['id']} {(winner.get('coding') or {}).get('tok_s')}")
        n = int(winner["variant"]["spec_tokens"])
        results.append(
            run_variant(
                {
                    "id": f"lmo_n{n}_s4_256k",
                    "spec_tokens": n,
                    "max_num_seqs": 4,
                    "max_model_len": NATIVE,
                    "yarn": False,
                }
            )
        )
        results.append(
            run_variant(
                {
                    "id": f"lmo_n{n}_s4_512k_yarn",
                    "spec_tokens": n,
                    "max_num_seqs": 4,
                    "max_model_len": 524288,
                    "yarn": True,
                }
            )
        )
        yarn512 = results[-1]
        if yarn512.get("ok"):
            results.append(
                run_variant(
                    {
                        "id": f"lmo_n{n}_s4_1m_yarn",
                        "spec_tokens": n,
                        "max_num_seqs": 4,
                        "max_model_len": 1048576,
                        "yarn": True,
                    }
                )
            )
        else:
            log("skip 1M YaRN because 512k did not boot/smoke")
    else:
        log("no MTP variant produced a coding result; leaving service at last attempt")

    summary = []
    for r in results:
        c = r.get("coding") or {}
        f = r.get("facts") or {}
        kv = r.get("kv") or {}
        summary.append(
            {
                "id": r.get("id"),
                "ok": r.get("ok"),
                "coding_tok_s": c.get("tok_s"),
                "facts_tok_s": f.get("tok_s"),
                "kv_tokens": kv.get("kv_tokens"),
                "live_ctx": r.get("max_model_len_live"),
                "error": (r.get("error") or "")[:240],
            }
        )
    log("SUMMARY " + json.dumps(summary, indent=2))
    (ROOT / "run" / "ornith15-tune-summary.json").write_text(
        json.dumps({"summary": summary, "results": results}, indent=2) + "\n",
        encoding="utf-8",
    )
    return 0 if any(r.get("ok") for r in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
