#!/usr/bin/env python3
"""Add Qwen agent tool-call flags to write_eugr_service scaffold."""
from __future__ import annotations

import sys
from pathlib import Path

TARGET = Path("/opt/spark/scripts/spark-inference.py")

HELPER = '''
def eugr_qwen_agent_lines(model_dir: Path) -> str:
    if not is_qwen36_family(model_dir):
        return ""
    return (
        "    --enable-auto-tool-choice \\\\\n"
        "    --tool-call-parser qwen3_xml \\\\\n"
    )


'''

OLD = """    lmo_line = eugr_language_model_only_line(model_dir)
    env_block = eugr_nvfp4_env_yaml() if weight_format == "nvfp4" else ""
    max_len = infer_max_model_len(model_dir, weight_format)
    path = SERVICES_DIR / f"eugr-{profile_id}.yaml"
    content = f\"\"\"# Generated by spark-inference recipe scaffold ({profile_id})
"""

NEW = """    lmo_line = eugr_language_model_only_line(model_dir)
    agent_line = eugr_qwen_agent_lines(model_dir)
    env_block = eugr_nvfp4_env_yaml() if weight_format == "nvfp4" else ""
    max_len = infer_max_model_len(model_dir, weight_format)
    path = SERVICES_DIR / f"eugr-{profile_id}.yaml"
    content = f\"\"\"# Generated by spark-inference recipe scaffold ({profile_id})
"""

CMD_OLD = """    --trust-remote-code \\\\
    --kv-cache-dtype auto \\\\
{attn_line}{lmo_line}{moe_line}    --gpu-memory-utilization {{gpu_memory_utilization}} \\\\
"""

CMD_NEW = """    --trust-remote-code \\\\
{agent_line}    --kv-cache-dtype auto \\\\
{attn_line}{lmo_line}{moe_line}    --gpu-memory-utilization {{gpu_memory_utilization}} \\\\
"""


def main() -> int:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else TARGET
    text = path.read_text()
    if "def eugr_qwen_agent_lines" not in text:
        text = text.replace(
            "def eugr_language_model_only_line(model_dir: Path) -> str:",
            HELPER + "def eugr_language_model_only_line(model_dir: Path) -> str:",
        )
    if "agent_line = eugr_qwen_agent_lines" not in text:
        text = text.replace(OLD, NEW, 1)
    if "{agent_line}" not in text.split("def write_eugr_service")[1].split("def discover_dflash")[0]:
        text = text.replace(CMD_OLD, CMD_NEW, 1)
    path.write_text(text)
    import py_compile

    py_compile.compile(str(path), doraise=True)
    print("patched", path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
